### ISSUE TITLE
datecmp, timecmp 에서 sametime 만을 출력

### ISSUE THREAD

**Issue by shin-haedam** [soemthlng/OSS_Assign2#22]
시간과 날짜 비교 함수가 계속 sametime 만을 출력합니다

time1과 time2가 모두 text2의 시간정보를 입력받는것으로 추정됩니다

**Comment by gregchu1** [comment]
![3](https://user-images.githubusercontent.com/37770967/39307011-33b74410-4951-11e8-861f-cea4c7f25ff2.jpg)
![4](https://user-images.githubusercontent.com/37770967/39307013-33f83c90-4951-11e8-80db-c44acfbbb98a.jpg)

time1 함수를 실행하고 바로 시간정보를 출력하면 정상적으로 작동합니다.
하지만 time2 함수를 실행하면 time1에 time2의 시간정보가 덧붙여지네요.

**Comment by gregchu1** [comment]
![6](https://user-images.githubusercontent.com/37770967/39309248-13396bea-4957-11e8-8559-5debec3cb79a.jpg)
![5](https://user-images.githubusercontent.com/37770967/39309249-13c1d9d0-4957-11e8-9df9-8ead1d8f18c6.jpg)

localtime 함수 자체가 불안정한 함수여서 (전역변수로 설정할 경우 포인터가 같은 값을 가져오는 일이 발생) localtime_r 함수를 대신 사용해봤습니다. gcc가 작동하기는 하지만 조금 사용법이 미숙해서 warning이 발생하네요. 대신 결과를 출력해보면 정상적으로 작동합니다.

**Comment by shin-haedam** [comment]
일단 이 버전으로 merge해서 워닝 해결방법을 이슈로 올리는건 어떨까요?

**Comment by gregchu1** [comment]
![50](https://user-images.githubusercontent.com/37770967/39317875-349a6db0-496c-11e8-8445-31a8caab0e63.jpg)
localtime 함수를 사용하는 대신 각 함수에 temp1과 temp2라는 tm 구조체를 만들고,
time1과 time2 구조체 포인터에 localtime으로 시간값을 받아온 이후,
각각 temp1과 temp2에 time 값들을 메모리 복사하고 temp1과 temp2의 시간 값을 이용하면 어떨까요?
우선 제가 시간 비교 함수를 ->의 포인터 형식에서 temp1.tm_min 이런식으로 바꿔서 진행해보겠습니다.

**Comment by shin-haedam** [comment]
![error](https://user-images.githubusercontent.com/31644563/39319153-34e30864-49bb-11e8-8f89-f0c888100d93.PNG)

저 오류뜨는데요,,,,

근데 그거 시간의 각각의 정보로 접근했을때 제대로 나오나요?
min이라던가, mon같은거요

**Comment by gregchu1** [comment]
음 저는 코딩은 되는데 실행해보면 오류가 나네요.

**Comment by gregchu1** [comment]
localtime은 내부적으로 포인터로 가지고 있고 이를 이용해 값을 변경하기 때문에 값이 함수를 호출할 때마다 내용이 바뀐다고 합니다. 이를 해결하기 위한 첫번째 방법으로 memcpy로 해당 구조체를 새로운 공간에 복사한 후 그 값을 불러오는 방식을 사용했지만, 이는 time 함수 내부에 공간(배열)이 선언되므로 static 변수도 불가능하고 비교 함수에서 사용할 수가 없었습니다. 전역 변수로 해당 공간을 선언하지 않는한 사용이 불가능하기에 이는 포기했습니다.
두 번째로 localtime_r 함수를 사용하는 방법인데 이는 localtime이 가지고 있는 전형적인 정적 구조체 포인터의 단점을 없애기 위해 만들어진 함수입니다. 단 이 역시도 별도의 정적 구조체를 선언해서 사용해야 하는데 memcpy와 마찬가지로 함수 외부로의 접근이 불가능하기 때문에 전역 변수로 선언해야합니다. 하지만 이 방법을 사용할 경우 main 함수에 있는 전역 변수인 struct tm * time1, time2를 사용하지 않습니다. 따라서 main 함수를 최대한 변경하지 않기 위해 포인터 대신 struct tm time1, time2의 구조체로 사용했습니다.
![81](https://user-images.githubusercontent.com/37770967/39322455-7b32021c-4979-11e8-8b4b-c9a7f8c368f7.jpg)
따라서 filetime1과 filetime2 함수는 다음과 같이 간략하게 줄일 수 있으며 (에러는 stat 함수에서 검증)
![82](https://user-images.githubusercontent.com/37770967/39322486-8ff39ddc-4979-11e8-97d3-835f156eba3c.jpg)
구조체 포인터로 time1->tm_min 처럼 접근하는 방법 대신, 바로 time1.tm_min의 구조체 접근 방식으로 코드를 수정했습니다.
![83](https://user-images.githubusercontent.com/37770967/39322524-afca8986-4979-11e8-95f8-6296575bcb96.jpg)

그 결과 정상적인 코드 수행이 가능합니다.
![80](https://user-images.githubusercontent.com/37770967/39322538-bb853d2a-4979-11e8-9d6c-14b71acaca77.jpg)

**Comment by soemthlng** [comment]
그나마 제일 나은 방법 같네요

**Comment by shin-haedam** [comment]
와 대단합니다!!
일단은 해결 된 것을로 알고 이슈 닫을게요
